version: '3'
services:
  app:
    build:
      context: .
    restart: always
    container_name: relay_switcher_app
    environment:
      HLK_SW16_HOST: 192.168.0.200
      HLK_SW16_PORT: 8080
      MQTT_SENDER_HOST: mqttsender:8080
